### ISSUE TITLE
MuSig2 support

### ISSUE THREAD

**Issue by bigspider** [LedgerHQ/app-bitcoin-new#208]
Extend wallet policies with `musig` support, as tentatively specified [here](https://github.com/achow101/bips/blob/musig2-descriptors/bip-musig2-descriptors.mediawiki).

For wallet policies, expressions of the form:

```
musig(KEY, ..., KEY)/<M,N>/*
musig(KEY, ..., KEY)/**
```
will suffice; `KEY` can be restricted to xpubs (although it's possible to generalize to other key expressions if there are use cases). It is unclear if there is any benefit in supporting things like `musig(KEY/**, ..., KEY/**)`, which seems [inherently inefficient](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-November/022132.html).

References
  - [BIP-0327](https://github.com/bitcoin/bips/blob/master/bip-0327.mediawiki)
  - The drafts BIPs for Musig2: https://github.com/bitcoin/bips/compare/master...achow101:bips:musig2.
  - PR for MuSig2 support in libsecp256k1: https://github.com/bitcoin-core/secp256k1/issues/1452

Tasks:
   - Bitcoin app
     - [x] Wallet policy parsing of `musig` descriptors
     - [x] Update specs for PSBT fields (aggregate key is now a plain key and not x-only)
     - [x] Aggregate xpub derivation for `musig` descriptor
     - [x] Address generation for policies with `musig` descriptor.
     - [x] Update to sorted `musig()` (per [this](https://github.com/bitcoin/bips/pull/1540#issuecomment-2059110591))
     - [x] Review sanity rules (e.g.: repeated xpubs in wallet policy) in the presence of `musig`
     - [x] Transaction-level signing session logic
     - [x] Pubnonce generation
     - [x] Partial signature in signing logic.
     - [x] Compute the aggregate key only once for the placeholder
     - [x] Sign the second round silently if both rounds are executed back-to-back.
   - Client libraries:
     - [x] Extend processing of YIELD to understand pubnonces and partial signatures (all clients)
     - [x] Add musig() xpub generation to python client
     - [x] Update to sorted `musig()` (per [this](https://github.com/bitcoin/bips/pull/1540#issuecomment-2059110591))
     - [x] <del>Add musig() xpub generation to Rust client</del> moved to #303
     - [x] <del>Add musig() xpub generation to JS client </del> moved to #303
   - UX
     - [x] Figure out what to show when no signature is produced, and only pubnonces (instead of Transaction Signed)
   - Tests:
     - [x] Address generation
     - [x] Implement cosigner logic and psbt partial signature aggregation in the python test suite
     - [x] <del>Extensive tests</del> moved to #302
     - [x] Figure out how to optimize the CI to not recompile bitcoin every time

**Comment by bigspider** [comment]
[BIP-0327](https://github.com/bitcoin/bips/blob/master/bip-0327.mediawiki) discusses the necessity to keep some state during a signing session. However, a "signing session" in BIP-0327 only refers to the production of a single signature.

In the typical signing flow of a wallet, it's more logical to consider a _session_ at the level of an entire transaction. All of the inputs of the transactions are likely to be obtained from the same descriptor, and the signer would produce the pubnonce/signature for all of them at the same time.

Therefore, in the flow of BIP-0327, you would expect _one MuSig2 signing session per input_ to be active at the same time. That's problematic as it would require to persist state for an unbounded number of signing sessions.

Instead, we want a _psbt-level session_ with a small state persisted on chain, that allows to complete a full signing flow for the entire PSBT; the necessary state for the each actual session for each internal input (possibly, one session per-input and per-placeholder of the wallet policy) can be syntethically generated.

### Signing flow

For now, we assume that the app can handle a single psbt-level session; this could be generalized to multiple parallel psbt-level sessions in the future.

In the following, a _session_ always refers to the psbt-level signing session.

**Phase 1: pubnonce generation:** A PSBT is sent to the bitcoin app, and it does not contain any pubnonce.
If a session already exists, it is deleted from the persistent memory.
A new session is created in volatile memory.
The app produces a fresh random number `rand_root`, and saves it in the current session.
The app generates the randomness for the $i$-th placeholder and for the $j$-th input as: $rand_{i,j} = SHA256(rand\\_root || i || j)$ (with a fixed-length encoding of $i$ and $j$). That is used as the `rand'` value in `NonceGen` for that input/placeholder pair.
At completion (after all the pubnonces are returned), the session is copied into the persistent memory.

**Phase 2: partial signature generation:** A PSBT is sent to the bitcoin app, and contains the pubnonces. **
*A copy of the session is stored in the volatile memory, and the session is deleted from the persistent memory*.
The app continues the signing flow, regenerating the secnonces with the syntetic randomness `rand_{i,j}`. 


**Observation:** if the optional parameters are passed to the `NonceGen` function, they will depend on the transaction data present in the PSBT. Therefore, there is no guarantee that they will be unchanged the next time the PSBT is provided. However, that does not constitute a security risk, as those parameters are only used as additional sources of entropy in `NonceGen`. A malicious client can't affect the _secnonce_/_pubnonce_ pairs in any predictable way, since the `rand_root` never leaves the device.
